#!/bin/sh

# Name of the daemon
DAEMON_NAME="aesdsocket"

# Options for the daemon
DAEMON_OPTS="-d"


case "$1" in
    start)
        echo "Starting $DAEMON_NAME..."
        start-stop-daemon -S -n $DAEMON_NAME -a /usr/bin/$DAEMON_NAME -- $DAEMON_OPTS
        echo "$DAEMON_NAME started."
        ;;
    stop)
        echo "Stopping $DAEMON_NAME..."
        start-stop-daemon -K -n $DAEMON_NAME
        echo "$DAEMON_NAME stopped."
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
